import sys
from datetime import datetime
import urllib.request
import urllib.parse
import json
import argparse

def get_speed_cameras_from_overpass_api():
    overpass_url = "http://overpass-api.de/api/interpreter"
# TODO: get and parse nwr instead of node
    overpass_query = """[out:json][timeout:1000];
node["highway"="speed_camera"];
out geom;
"""
    data = urllib.parse.urlencode({'data': overpass_query}).encode()
    req = urllib.request.Request(overpass_url, data=data, method='GET')
    with urllib.request.urlopen(req) as response:
        return json.loads(response.read())['elements']

def get_cameras():
    overpass = get_speed_cameras_from_overpass_api()
    cameras = []
    invalid_maxspeed_cnt = 0
    for node in overpass:
        lat, lon = float(node['lat']), float(node['lon'])
        try:
            maxspeed = node['tags']['maxspeed']
        except:
            maxspeed = '0'
        try:
            limit = int(maxspeed.split()[0])
        except:
            invalid_maxspeed_cnt += 1
            limit = 0
        cameras.append({'id': node['id'], 'lat': lat, 'lon': lon, 'limit': limit})
    print(f"Found {invalid_maxspeed_cnt} cameras with invalid maxspeed value")
    return cameras

def generate_c_file(output_file, data_list):
    with open(output_file, 'w') as f:
        current_date = datetime.now().strftime("%d-%m-%Y %H:%M:%S")
        cams_list = ""
        for c in data_list:
            lat = c["lat"]
            lon = c["lon"]
            limit = c["limit"]
            id = c["id"]
            osv_url = f"https://www.openstreetmap.org/node/{id}"
            gmaps_url = f"https://maps.google.com/maps?q=&layer=c&cbll={lat},{lon}"
            line = f'    {{ {lat:.7f}f, {lon:.7f}f, {limit} }}, // {osv_url} // {gmaps_url}\n'
            cams_list += line

        f.write(f"""\
// This file was generated by a script on {current_date}
// Do not edit this file manually

#pragma once

#include <pico/platform/sections.h>
#include "cams.h"

static const struct cams_camera_info __in_flash("cams_list") cams_list[] = {{
{cams_list}
}};

static const size_t cams_list_length = sizeof(cams_list) / sizeof(cams_list[0]);
""")

def generate_js_file(output_file, data_list):
    with open(output_file, 'w') as f:
            current_date = datetime.now().strftime("%d-%m-%Y %H:%M:%S")
            contents = ''
            contents += f'// This file was generated by a script on {current_date}\n'
            contents += f'// Do not edit this file manually\n'
            contents += '\n'
            contents += f'const cams_list = [ '
            for c in data_list:
                lat = c["lat"]
                lon = c["lon"]
                contents += f'{{ lat: {lat:.7f}, lng: {lon:.7f} }}, '
            contents += f' ];\n'
            contents += f'\n'
            contents += f'window.cams_list = cams_list;\n'
            f.write(contents)

def main(output_file_h, output_file_js):
    print("Fetching cameras...")
    cameras = get_cameras()
    if len(cameras) == 0:
        print("No cameras found")
        sys.exit(1)
    cameras_sorted = sorted(cameras, key=lambda x: (x['lat'], x['lon']))
    print(f"Found total {len(cameras_sorted)} cameras")
    print(f"Generating C header file: {output_file_h}")
    generate_c_file(output_file_h, cameras_sorted)
    print(f"Generating JS file: {output_file_js}")
    generate_js_file(output_file_js, cameras_sorted)
    print("Done")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    if len(sys.argv) != 3:
        print("Usage: python3 fetch.py filename.h filename.js")
        sys.exit(1)

    output_file_h = sys.argv[1]
    output_file_js = sys.argv[2]
    main(output_file_h, output_file_js)
