name: build-and-release
on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  BUILD_TYPE: Release

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Update camera list
        run: python3 ${{github.workspace}}/scripts/fetch_cameras/fetch.py ${{github.workspace}}/src/cams/cams_list.h

      - name: Commit and push changes
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add ${{github.workspace}}/src/cams/cams_list.h
          git diff-index --quiet HEAD || git commit -m "Update cameras list"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake gcc-arm-none-eabi

      - name: Checkout pico-sdk
        uses: actions/checkout@v4
        with:
          repository: raspberrypi/pico-sdk
          ref: develop
          path: ${{github.workspace}}/pico-sdk

      - name: Checkout pico-sdk submodules
        working-directory: ${{github.workspace}}/pico-sdk
        run: git submodule update --init

      - name: Create build directory
        run: mkdir -p ${{github.workspace}}/build

      - name: Configure CMake
        working-directory: ${{github.workspace}}/build
        run: PICO_SDK_PATH=${{github.workspace}}/pico-sdk cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config $BUILD_TYPE --parallel $(nproc)

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: catchcam.uf2
          path: ${{github.workspace}}/build/catchcam.uf2

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          draft: false
          files: ${{github.workspace}}/build/catchcam.uf2